apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: react-app
        image: ashwinraju/docker_react_image:v1
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "256Mi"  # Increased from 64Mi to 256Mi
            cpu: "500m"     # Optional increase if CPU resources are also constrained
          limits:
            memory: "512Mi"  # Increased from 128Mi to 512Mi
            cpu: "1000m"    # Optional increase to 1 CPU if needed